# Generated by Django 3.1.7 on 2021-04-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guid", models.UUIDField(db_index=True, unique=True)),
                (
                    "unit_name",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="ticker symbol"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="asset name"
                    ),
                ),
                ("asset_id", models.PositiveIntegerField(unique=True)),
                ("description", models.TextField()),
                (
                    "application_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "escrow_address",
                    models.CharField(blank=True, max_length=58, null=True, unique=True),
                ),
                (
                    "holding_address",
                    models.CharField(blank=True, max_length=58, null=True),
                ),
                ("creator_address", models.CharField(max_length=58)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DA", "Deployed asset"),
                            ("DC", "Deployed contract"),
                            ("RD", "Ready to use"),
                        ],
                        default="DA",
                        max_length=2,
                    ),
                ),
                ("image", models.FileField(upload_to="")),
                ("last_round", models.PositiveIntegerField(default=0)),
                ("last_check", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Asset",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(max_length=58)),
                ("is_staff", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "op_type",
                    models.CharField(
                        choices=[
                            ("ASK", "Ask"),
                            ("BID", "Bid"),
                            ("BUY_NOW", "Buy Now"),
                            ("SELL_NOW", "Sell Now"),
                        ],
                        max_length=8,
                    ),
                ),
                ("value", models.PositiveIntegerField(blank=True, null=True)),
                ("tx_id", models.CharField(blank=True, max_length=58, null=True)),
                ("sender", models.CharField(blank=True, max_length=58, null=True)),
                ("account", models.CharField(blank=True, max_length=58, null=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("is_executed", models.BooleanField(default=False)),
                ("is_pending", models.BooleanField(default=False)),
                ("block_number", models.PositiveIntegerField(blank=True, null=True)),
                ("block_time", models.DateTimeField(blank=True, null=True)),
                ("blob", models.BinaryField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.asset",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.UniqueConstraint(
                condition=models.Q(tx_id__isnull=False),
                fields=("tx_id",),
                name="unique__name__when__tx_id__not_null",
            ),
        ),
    ]
